EXEC sp_serveroption 'AZURE_BRENDA', 'rpc out', true;
EXEC sp_serveroption 'AZURE_BRENDA', 'rpc', true;

EXEC sp_linkedservers;

SELECT *
FROM OPENQUERY([AZURE-MARIO], 'SELECT * FROM dbo.datoscovid_centroSur');


SELECT *
FROM OPENQUERY([AZURE-ALAN], 'SELECT * FROM dbo.datoscovid_noreste');


SELECT *
FROM OPENQUERY([MYSQL_ALAN2], 'SELECT * FROM covidhistorico.datoscovid_suroeste');


------------------------------------------------------------------
--crear tabla en la que se añadiran los datos
EXEC('
CREATE TABLE [dbo].[datoscovid_occidente](
	[FECHA_ACTUALIZACION] [nvarchar](15) NULL,
	[ID_REGISTRO] [varchar](15) NOT NULL,
	[ORIGEN] [int] NULL,
	[SECTOR] [int] NULL,
	[ENTIDAD_UM] [nvarchar](15) NULL,
	[SEXO] [int] NULL,
	[ENTIDAD_NAC] [nvarchar](15) NULL,
	[ENTIDAD_RES] [nvarchar](15) NULL,
	[MUNICIPIO_RES] [nvarchar](15) NULL,
	[TIPO_PACIENTE] [int] NULL,
	[FECHA_INGRESO] [nvarchar](20) NULL,
	[FECHA_SINTOMAS] [nvarchar](15) NULL,
	[FECHA_DEF] [nvarchar](15) NULL,
	[INTUBADO] [int] NULL,
	[NEUMONIA] [int] NULL,
	[EDAD] [nvarchar](7) NULL,
	[NACIONALIDAD] [int] NULL,
	[EMBARAZO] [int] NULL,
	[HABLA_LENGUA_INDIG] [int] NULL,
	[INDIGENA] [int] NULL,
	[DIABETES] [int] NULL,
	[EPOC] [int] NULL,
	[ASMA] [int] NULL,
	[INMUSUPR] [int] NULL,
	[HIPERTENSION] [int] NULL,
	[OTRA_COM] [int] NULL,
	[CARDIOVASCULAR] [int] NULL,
	[OBESIDAD] [int] NULL,
	[RENAL_CRONICA] [int] NULL,
	[TABAQUISMO] [int] NULL,
	[OTRO_CASO] [int] NULL,
	[TOMA_MUESTRA_LAB] [int] NULL,
	[RESULTADO_LAB] [int] NULL,
	[TOMA_MUESTRA_ANTIGENO] [int] NULL,
	[RESULTADO_ANTIGENO] [int] NULL,
	[CLASIFICACION_FINAL] [int] NULL,
	[MIGRANTE] [int] NULL,
	[PAIS_NACIONALIDAD] [nvarchar](50) NULL,
	[PAIS_ORIGEN] [nvarchar](50) NULL,
	[UCI] [nvarchar](50) NULL)
') AT [AZURE_BRENDA];

EXEC('
CREATE TABLE [dbo].[datoscovid_oriente](
	[FECHA_ACTUALIZACION] [nvarchar](15) NULL,
	[ID_REGISTRO] [varchar](15) NOT NULL,
	[ORIGEN] [int] NULL,
	[SECTOR] [int] NULL,
	[ENTIDAD_UM] [nvarchar](15) NULL,
	[SEXO] [int] NULL,
	[ENTIDAD_NAC] [nvarchar](15) NULL,
	[ENTIDAD_RES] [nvarchar](15) NULL,
	[MUNICIPIO_RES] [nvarchar](15) NULL,
	[TIPO_PACIENTE] [int] NULL,
	[FECHA_INGRESO] [nvarchar](20) NULL,
	[FECHA_SINTOMAS] [nvarchar](15) NULL,
	[FECHA_DEF] [nvarchar](15) NULL,
	[INTUBADO] [int] NULL,
	[NEUMONIA] [int] NULL,
	[EDAD] [nvarchar](7) NULL,
	[NACIONALIDAD] [int] NULL,
	[EMBARAZO] [int] NULL,
	[HABLA_LENGUA_INDIG] [int] NULL,
	[INDIGENA] [int] NULL,
	[DIABETES] [int] NULL,
	[EPOC] [int] NULL,
	[ASMA] [int] NULL,
	[INMUSUPR] [int] NULL,
	[HIPERTENSION] [int] NULL,
	[OTRA_COM] [int] NULL,
	[CARDIOVASCULAR] [int] NULL,
	[OBESIDAD] [int] NULL,
	[RENAL_CRONICA] [int] NULL,
	[TABAQUISMO] [int] NULL,
	[OTRO_CASO] [int] NULL,
	[TOMA_MUESTRA_LAB] [int] NULL,
	[RESULTADO_LAB] [int] NULL,
	[TOMA_MUESTRA_ANTIGENO] [int] NULL,
	[RESULTADO_ANTIGENO] [int] NULL,
	[CLASIFICACION_FINAL] [int] NULL,
	[MIGRANTE] [int] NULL,
	[PAIS_NACIONALIDAD] [nvarchar](50) NULL,
	[PAIS_ORIGEN] [nvarchar](50) NULL,
	[UCI] [nvarchar](50) NULL)
') AT [AZURE_BRENDA];


--HACER FRAGMENTACIÓN DE TABLA DE DATOS COVID A ESTA BASE DE DATOS
INSERT INTO OPENQUERY([AZURE_BRENDA], 'SELECT * FROM bdd20252.dbo.datoscovid_occidente')
SELECT *
FROM covidHistorico.dbo.datoscovid
WHERE ENTIDAD_RES IN (18, 14, 06, 16);

INSERT INTO OPENQUERY([AZURE_BRENDA], 'SELECT * FROM bdd.dbo.datoscovid_oriente')
SELECT *
FROM covidHistorico.dbo.datoscovid
WHERE ENTIDAD_RES IN (30, 21, 29);


--CONSULTAS
-- CONSULTA 3
WITH TotalMorbilidades AS (
    -- Consultando para AZURE-ALAN (Nodos de Noroeste y Noreste)
    SELECT 
        CAST(SUM(CASE WHEN DIABETES = 1 THEN 1 ELSE 0 END) AS DECIMAL(18,2)) AS Total_DIABETES,
        CAST(SUM(CASE WHEN HIPERTENSION = 1 THEN 1 ELSE 0 END) AS DECIMAL(18,2)) AS Total_HIPERTENSION,
        CAST(SUM(CASE WHEN OBESIDAD = 1 THEN 1 ELSE 0 END) AS DECIMAL(18,2)) AS Total_OBESIDAD,
        COUNT(*) AS Total_Casos
    FROM OPENQUERY([AZURE-ALAN], 'SELECT DIABETES, HIPERTENSION, OBESIDAD, CLASIFICACION_FINAL FROM datoscovid_noroeste WHERE CLASIFICACION_FINAL IN (1, 2, 3)')
    UNION ALL
    SELECT 
        CAST(SUM(CASE WHEN DIABETES = 1 THEN 1 ELSE 0 END) AS DECIMAL(18,2)) AS Total_DIABETES,
        CAST(SUM(CASE WHEN HIPERTENSION = 1 THEN 1 ELSE 0 END) AS DECIMAL(18,2)) AS Total_HIPERTENSION,
        CAST(SUM(CASE WHEN OBESIDAD = 1 THEN 1 ELSE 0 END) AS DECIMAL(18,2)) AS Total_OBESIDAD,
        COUNT(*) AS Total_Casos
    FROM OPENQUERY([AZURE-ALAN], 'SELECT DIABETES, HIPERTENSION, OBESIDAD, CLASIFICACION_FINAL FROM datoscovid_noreste WHERE CLASIFICACION_FINAL IN (1, 2, 3)')

    -- Consultando para AZURE-MARIO (Nodos de Centronorte y Centrosur)
    UNION ALL
    SELECT 
        CAST(SUM(CASE WHEN DIABETES = 1 THEN 1 ELSE 0 END) AS DECIMAL(18,2)) AS Total_DIABETES,
        CAST(SUM(CASE WHEN HIPERTENSION = 1 THEN 1 ELSE 0 END) AS DECIMAL(18,2)) AS Total_HIPERTENSION,
        CAST(SUM(CASE WHEN OBESIDAD = 1 THEN 1 ELSE 0 END) AS DECIMAL(18,2)) AS Total_OBESIDAD,
        COUNT(*) AS Total_Casos
    FROM OPENQUERY([AZURE-MARIO], 'SELECT DIABETES, HIPERTENSION, OBESIDAD, CLASIFICACION_FINAL FROM datoscovid_centronorte WHERE CLASIFICACION_FINAL IN (1, 2, 3)')
    UNION ALL
    SELECT 
        CAST(SUM(CASE WHEN DIABETES = 1 THEN 1 ELSE 0 END) AS DECIMAL(18,2)) AS Total_DIABETES,
        CAST(SUM(CASE WHEN HIPERTENSION = 1 THEN 1 ELSE 0 END) AS DECIMAL(18,2)) AS Total_HIPERTENSION,
        CAST(SUM(CASE WHEN OBESIDAD = 1 THEN 1 ELSE 0 END) AS DECIMAL(18,2)) AS Total_OBESIDAD,
        COUNT(*) AS Total_Casos
    FROM OPENQUERY([AZURE-MARIO], 'SELECT DIABETES, HIPERTENSION, OBESIDAD, CLASIFICACION_FINAL FROM datoscovid_centrosur WHERE CLASIFICACION_FINAL IN (1, 2, 3)')

    -- Consultando para AZURE-BRENDA (Nodos de Occidente y Oriente)
    UNION ALL
    SELECT 
        CAST(SUM(CASE WHEN DIABETES = 1 THEN 1 ELSE 0 END) AS DECIMAL(18,2)) AS Total_DIABETES,
        CAST(SUM(CASE WHEN HIPERTENSION = 1 THEN 1 ELSE 0 END) AS DECIMAL(18,2)) AS Total_HIPERTENSION,
        CAST(SUM(CASE WHEN OBESIDAD = 1 THEN 1 ELSE 0 END) AS DECIMAL(18,2)) AS Total_OBESIDAD,
        COUNT(*) AS Total_Casos
    FROM OPENQUERY([AZURE-BRENDA], 'SELECT DIABETES, HIPERTENSION, OBESIDAD, CLASIFICACION_FINAL FROM datoscovid_occidente WHERE CLASIFICACION_FINAL IN (1, 2, 3)')
    UNION ALL
    SELECT 
        CAST(SUM(CASE WHEN DIABETES = 1 THEN 1 ELSE 0 END) AS DECIMAL(18,2)) AS Total_DIABETES,
        CAST(SUM(CASE WHEN HIPERTENSION = 1 THEN 1 ELSE 0 END) AS DECIMAL(18,2)) AS Total_HIPERTENSION,
        CAST(SUM(CASE WHEN OBESIDAD = 1 THEN 1 ELSE 0 END) AS DECIMAL(18,2)) AS Total_OBESIDAD,
        COUNT(*) AS Total_Casos
    FROM OPENQUERY([AZURE-BRENDA], 'SELECT DIABETES, HIPERTENSION, OBESIDAD, CLASIFICACION_FINAL FROM datoscovid_oriente WHERE CLASIFICACION_FINAL IN (1, 2, 3)')

    -- Consultando para MYSQL_ALAN (Nodos de Suroeste y Sureste)
    UNION ALL
    SELECT 
        CAST(SUM(CASE WHEN DIABETES = 1 THEN 1 ELSE 0 END) AS DECIMAL(18,2)) AS Total_DIABETES,
        CAST(SUM(CASE WHEN HIPERTENSION = 1 THEN 1 ELSE 0 END) AS DECIMAL(18,2)) AS Total_HIPERTENSION,
        CAST(SUM(CASE WHEN OBESIDAD = 1 THEN 1 ELSE 0 END) AS DECIMAL(18,2)) AS Total_OBESIDAD,
        COUNT(*) AS Total_Casos
    FROM OPENQUERY([MYSQL_CONEXION], 'SELECT DIABETES, HIPERTENSION, OBESIDAD, CLASIFICACION_FINAL FROM covidhistorico.datoscovid_suroeste WHERE CLASIFICACION_FINAL IN (1, 2, 3)')
    UNION ALL
    SELECT 
        CAST(SUM(CASE WHEN DIABETES = 1 THEN 1 ELSE 0 END) AS DECIMAL(18,2)) AS Total_DIABETES,
        CAST(SUM(CASE WHEN HIPERTENSION = 1 THEN 1 ELSE 0 END) AS DECIMAL(18,2)) AS Total_HIPERTENSION,
        CAST(SUM(CASE WHEN OBESIDAD = 1 THEN 1 ELSE 0 END) AS DECIMAL(18,2)) AS Total_OBESIDAD,
        COUNT(*) AS Total_Casos
    FROM OPENQUERY([MYSQL_CONEXION], 'SELECT DIABETES, HIPERTENSION, OBESIDAD, CLASIFICACION_FINAL FROM covidhistorico.datoscovid_sureste WHERE CLASIFICACION_FINAL IN (1, 2, 3)')
)

-- Calcular el porcentaje nacional
SELECT 
    CAST(SUM(Total_DIABETES) * 100.0 / SUM(Total_Casos) AS DECIMAL(18,2)) AS Porcentaje_Nacional_DIABETES,
    CAST(SUM(Total_HIPERTENSION) * 100.0 / SUM(Total_Casos) AS DECIMAL(18,2)) AS Porcentaje_Nacional_HIPERTENSION,
    CAST(SUM(Total_OBESIDAD) * 100.0 / SUM(Total_Casos) AS DECIMAL(18,2)) AS Porcentaje_Nacional_OBESIDAD
FROM TotalMorbilidades

-- CONSULTA 4:
SELECT DISTINCT entidad_res, MUNICIPIO_RES
FROM (
    -- Define a common collation, e.g., SQL_Latin1_General_CP1_CI_AS
    -- Cast string columns to NVARCHAR and apply the desired collation
    SELECT TOP 200
        CAST(entidad_res AS NVARCHAR(255)) COLLATE SQL_Latin1_General_CP1_CI_AS AS entidad_res,
        CAST(MUNICIPIO_RES AS NVARCHAR(255)) COLLATE SQL_Latin1_General_CP1_CI_AS AS MUNICIPIO_RES,
        CLASIFICACION_FINAL, -- Include other necessary columns
        HIPERTENSION,
        OBESIDAD,
        DIABETES,
        TABAQUISMO
    FROM OPENQUERY([MYSQL_CONEXION], 'SELECT entidad_res, MUNICIPIO_RES, CLASIFICACION_FINAL, HIPERTENSION, OBESIDAD, DIABETES, TABAQUISMO FROM covidHistorico.datoscovid_sureste')
    UNION ALL -- Use UNION ALL for performance and then GROUP BY handles distinct
    SELECT TOP 200
        CAST(entidad_res AS NVARCHAR(255)) COLLATE SQL_Latin1_General_CP1_CI_AS AS entidad_res,
        CAST(MUNICIPIO_RES AS NVARCHAR(255)) COLLATE SQL_Latin1_General_CP1_CI_AS AS MUNICIPIO_RES,
        CLASIFICACION_FINAL,
        HIPERTENSION,
        OBESIDAD,
        DIABETES,
        TABAQUISMO
    FROM OPENQUERY([MYSQL_CONEXION], 'SELECT entidad_res, MUNICIPIO_RES, CLASIFICACION_FINAL, HIPERTENSION, OBESIDAD, DIABETES, TABAQUISMO FROM covidHistorico.datoscovid_suroeste')
    UNION ALL
    SELECT TOP 1000
        CAST(entidad_res AS NVARCHAR(255)) COLLATE SQL_Latin1_General_CP1_CI_AS AS entidad_res,
        CAST(MUNICIPIO_RES AS NVARCHAR(255)) COLLATE SQL_Latin1_General_CP1_CI_AS AS MUNICIPIO_RES,
        CLASIFICACION_FINAL,
        HIPERTENSION,
        OBESIDAD,
        DIABETES,
        TABAQUISMO
    FROM OPENQUERY([AZURE-ALAN], 'SELECT entidad_res, MUNICIPIO_RES, CLASIFICACION_FINAL, HIPERTENSION, OBESIDAD, DIABETES, TABAQUISMO FROM dbo.datoscovid_noreste')
    UNION ALL
    SELECT TOP 1000
        CAST(entidad_res AS NVARCHAR(255)) COLLATE SQL_Latin1_General_CP1_CI_AS AS entidad_res,
        CAST(MUNICIPIO_RES AS NVARCHAR(255)) COLLATE SQL_Latin1_General_CP1_CI_AS AS MUNICIPIO_RES,
        CLASIFICACION_FINAL,
        HIPERTENSION,
        OBESIDAD,
        DIABETES,
        TABAQUISMO
    FROM OPENQUERY([AZURE-ALAN], 'SELECT entidad_res, MUNICIPIO_RES, CLASIFICACION_FINAL, HIPERTENSION, OBESIDAD, DIABETES, TABAQUISMO FROM dbo.datoscovid_noroeste')
    UNION ALL
    SELECT TOP 1000
        CAST(entidad_res AS NVARCHAR(255)) COLLATE SQL_Latin1_General_CP1_CI_AS AS entidad_res,
        CAST(MUNICIPIO_RES AS NVARCHAR(255)) COLLATE SQL_Latin1_General_CP1_CI_AS AS MUNICIPIO_RES,
        CLASIFICACION_FINAL,
        HIPERTENSION,
        OBESIDAD,
        DIABETES,
        TABAQUISMO
    FROM OPENQUERY([AZURE-MARIO], 'SELECT entidad_res, MUNICIPIO_RES, CLASIFICACION_FINAL, HIPERTENSION, OBESIDAD, DIABETES, TABAQUISMO FROM dbo.datoscovid_centronorte')
    UNION ALL
    SELECT TOP 1000
        CAST(entidad_res AS NVARCHAR(255)) COLLATE SQL_Latin1_General_CP1_CI_AS AS entidad_res,
        CAST(MUNICIPIO_RES AS NVARCHAR(255)) COLLATE SQL_Latin1_General_CP1_CI_AS AS MUNICIPIO_RES,
        CLASIFICACION_FINAL,
        HIPERTENSION,
        OBESIDAD,
        DIABETES,
        TABAQUISMO
    FROM OPENQUERY([AZURE-MARIO], 'SELECT entidad_res, MUNICIPIO_RES, CLASIFICACION_FINAL, HIPERTENSION, OBESIDAD, DIABETES, TABAQUISMO FROM dbo.datoscovid_centrosur')
    UNION ALL
    SELECT TOP 1000
        CAST(entidad_res AS NVARCHAR(255)) COLLATE SQL_Latin1_General_CP1_CI_AS AS entidad_res,
        CAST(MUNICIPIO_RES AS NVARCHAR(255)) COLLATE SQL_Latin1_General_CP1_CI_AS AS MUNICIPIO_RES,
        CLASIFICACION_FINAL,
        HIPERTENSION,
        OBESIDAD,
        DIABETES,
        TABAQUISMO
    FROM OPENQUERY([AZURE-BRENDA], 'SELECT entidad_res, MUNICIPIO_RES, CLASIFICACION_FINAL, HIPERTENSION, OBESIDAD, DIABETES, TABAQUISMO FROM dbo.datoscovid_occidente')
    UNION ALL
    SELECT TOP 1000
        CAST(entidad_res AS NVARCHAR(255)) COLLATE SQL_Latin1_General_CP1_CI_AS AS entidad_res,
        CAST(MUNICIPIO_RES AS NVARCHAR(255)) COLLATE SQL_Latin1_General_CP1_CI_AS AS MUNICIPIO_RES,
        CLASIFICACION_FINAL,
        HIPERTENSION,
        OBESIDAD,
        DIABETES,
        TABAQUISMO
    FROM OPENQUERY([AZURE-BRENDA], 'SELECT entidad_res, MUNICIPIO_RES, CLASIFICACION_FINAL, HIPERTENSION, OBESIDAD, DIABETES, TABAQUISMO FROM dbo.datoscovid_oriente')
) AS datos
WHERE CLASIFICACION_FINAL NOT IN ('1', '2', '3')
  AND HIPERTENSION = '1'
  AND OBESIDAD = '1'
  AND DIABETES = '1'
  AND TABAQUISMO = '1'
GROUP BY entidad_res, MUNICIPIO_RES;

-- CONSULTA 5:
WITH CasosRecuperados AS (
    -- Consultando para AZURE-ALAN (Nodos de Noroeste y Noreste)
    SELECT ce.entidad, COUNT(*) AS Casos_Recuperados
    FROM OPENQUERY([AZURE-ALAN], 'SELECT ENTIDAD_RES FROM datoscovid_noroeste WHERE NEUMONIA = 1 AND FECHA_DEF = ''9999-99-99'' AND CLASIFICACION_FINAL IN (''1'', ''2'', ''3'')') AS t1
    JOIN covidHistorico.dbo.cat_entidades ce ON t1.ENTIDAD_RES = ce.clave COLLATE SQL_Latin1_General_CP1_CI_AS
    GROUP BY ce.entidad

    UNION ALL

    SELECT ce.entidad, COUNT(*) AS Casos_Recuperados
    FROM OPENQUERY([AZURE-ALAN], 'SELECT ENTIDAD_RES FROM datoscovid_noreste WHERE NEUMONIA = 1 AND FECHA_DEF = ''9999-99-99'' AND CLASIFICACION_FINAL IN (''1'', ''2'', ''3'')') AS t2
    JOIN covidHistorico.dbo.cat_entidades ce ON t2.ENTIDAD_RES = ce.clave COLLATE SQL_Latin1_General_CP1_CI_AS
    GROUP BY ce.entidad
    
    -- Consultando para AZURE-MARIO (Nodos de Centronorte y Centrosur)
    UNION ALL
    SELECT ce.entidad, COUNT(*) AS Casos_Recuperados
    FROM OPENQUERY([AZURE-MARIO], 'SELECT ENTIDAD_RES FROM datoscovid_centronorte WHERE NEUMONIA = 1 AND FECHA_DEF = ''9999-99-99'' AND CLASIFICACION_FINAL IN (''1'', ''2'', ''3'')') AS t3
    JOIN covidHistorico.dbo.cat_entidades ce ON t3.ENTIDAD_RES = ce.clave COLLATE SQL_Latin1_General_CP1_CI_AS
    GROUP BY ce.entidad

    UNION ALL
    SELECT ce.entidad, COUNT(*) AS Casos_Recuperados
    FROM OPENQUERY([AZURE-MARIO], 'SELECT ENTIDAD_RES FROM datoscovid_centrosur WHERE NEUMONIA = 1 AND FECHA_DEF = ''9999-99-99'' AND CLASIFICACION_FINAL IN (''1'', ''2'', ''3'')') AS t4
    JOIN covidHistorico.dbo.cat_entidades ce ON t4.ENTIDAD_RES = ce.clave COLLATE SQL_Latin1_General_CP1_CI_AS
    GROUP BY ce.entidad
    
    -- Consultando para AZURE-BRENDA (Nodos de Occidente y Oriente)
    UNION ALL
    SELECT ce.entidad, COUNT(*) AS Casos_Recuperados
    FROM OPENQUERY([AZURE-BRENDA], 'SELECT ENTIDAD_RES FROM datoscovid_occidente WHERE NEUMONIA = 1 AND FECHA_DEF = ''9999-99-99'' AND CLASIFICACION_FINAL IN (''1'', ''2'', ''3'')') AS t5
    JOIN covidHistorico.dbo.cat_entidades ce ON t5.ENTIDAD_RES = ce.clave COLLATE SQL_Latin1_General_CP1_CI_AS
    GROUP BY ce.entidad

    UNION ALL
    SELECT ce.entidad, COUNT(*) AS Casos_Recuperados
    FROM OPENQUERY([AZURE-BRENDA], 'SELECT ENTIDAD_RES FROM datoscovid_oriente WHERE NEUMONIA = 1 AND FECHA_DEF = ''9999-99-99'' AND CLASIFICACION_FINAL IN (''1'', ''2'', ''3'')') AS t6
    JOIN covidHistorico.dbo.cat_entidades ce ON t6.ENTIDAD_RES = ce.clave COLLATE SQL_Latin1_General_CP1_CI_AS
    GROUP BY ce.entidad

    -- Consultando para MYSQL_ALAN (Nodos de Suroeste y Sureste)
    UNION ALL
    SELECT ce.entidad, COUNT(*) AS Casos_Recuperados
    FROM OPENQUERY([MYSQL_CONEXION], 'SELECT ENTIDAD_RES FROM covidhistorico.datoscovid_suroeste WHERE NEUMONIA = 1 AND FECHA_DEF = ''9999-99-99'' AND CLASIFICACION_FINAL IN (''1'', ''2'', ''3'')') AS t7
    JOIN covidHistorico.dbo.cat_entidades ce ON t7.ENTIDAD_RES = ce.clave COLLATE SQL_Latin1_General_CP1_CI_AS
    GROUP BY ce.entidad

    UNION ALL
    SELECT ce.entidad, COUNT(*) AS Casos_Recuperados
    FROM OPENQUERY([MYSQL_CONEXION], 'SELECT ENTIDAD_RES FROM covidhistorico.datoscovid_sureste WHERE NEUMONIA = 1 AND FECHA_DEF = ''9999-99-99'' AND CLASIFICACION_FINAL IN (''1'', ''2'', ''3'')') AS t8
    JOIN covidHistorico.dbo.cat_entidades ce ON t8.ENTIDAD_RES = ce.clave COLLATE SQL_Latin1_General_CP1_CI_AS
    GROUP BY ce.entidad
)

-- Seleccionar el total de casos recuperados por entidad a nivel nacional
SELECT 
    entidad, 
    SUM(Casos_Recuperados) AS Casos_Recuperados_Totales
FROM CasosRecuperados
GROUP BY entidad
ORDER BY Casos_Recuperados_Totales DESC;

-- CONSULTA 7
SELECT año, mes, NUM_REGISTROS, ENTIDAD_RES
FROM (
    SELECT 
        YEAR(FECHA_INGRESO) AS año, 
        MONTH(FECHA_INGRESO) AS mes, 
        COUNT(*) AS NUM_REGISTROS,
        ENTIDAD_RES, 
        MUNICIPIO_RES, 
        ROW_NUMBER() OVER (PARTITION BY ENTIDAD_RES ORDER BY COUNT(*) DESC) AS RowNum
    FROM
    (
        SELECT TOP 1000 FECHA_INGRESO, CLASIFICACION_FINAL, 
               CAST(ENTIDAD_RES AS NVARCHAR(MAX)) COLLATE SQL_Latin1_General_CP1_CI_AS AS ENTIDAD_RES,
               CAST(MUNICIPIO_RES AS NVARCHAR(MAX)) COLLATE SQL_Latin1_General_CP1_CI_AS AS MUNICIPIO_RES
        FROM OPENQUERY([AZURE-ALAN], 'SELECT FECHA_INGRESO, CLASIFICACION_FINAL, ENTIDAD_RES, MUNICIPIO_RES FROM dbo.datoscovid_noroeste')
        UNION ALL -- Use UNION ALL for performance if duplicates are acceptable or handled later
        SELECT TOP 1000 FECHA_INGRESO, CLASIFICACION_FINAL, 
               CAST(ENTIDAD_RES AS NVARCHAR(MAX)) COLLATE SQL_Latin1_General_CP1_CI_AS AS ENTIDAD_RES,
               CAST(MUNICIPIO_RES AS NVARCHAR(MAX)) COLLATE SQL_Latin1_General_CP1_CI_AS AS MUNICIPIO_RES
        FROM OPENQUERY([AZURE-ALAN], 'SELECT FECHA_INGRESO, CLASIFICACION_FINAL, ENTIDAD_RES, MUNICIPIO_RES FROM dbo.datoscovid_noreste')
		
        SELECT TOP 1000 FECHA_INGRESO, CLASIFICACION_FINAL, 
               CAST(ENTIDAD_RES AS NVARCHAR(MAX)) COLLATE SQL_Latin1_General_CP1_CI_AS AS ENTIDAD_RES,
               CAST(MUNICIPIO_RES AS NVARCHAR(MAX)) COLLATE SQL_Latin1_General_CP1_CI_AS AS MUNICIPIO_RES
        FROM OPENQUERY([MYSQL_CONEXION], 'SELECT FECHA_INGRESO, CLASIFICACION_FINAL, ENTIDAD_RES, MUNICIPIO_RES FROM covidhistorico.datoscovid_suroeste')
        UNION ALL
        SELECT TOP 1000 FECHA_INGRESO, CLASIFICACION_FINAL, 
               CAST(ENTIDAD_RES AS NVARCHAR(MAX)) COLLATE SQL_Latin1_General_CP1_CI_AS AS ENTIDAD_RES,
               CAST(MUNICIPIO_RES AS NVARCHAR(MAX)) COLLATE SQL_Latin1_General_CP1_CI_AS AS MUNICIPIO_RES
        FROM OPENQUERY([MYSQL_CONEXION], 'SELECT FECHA_INGRESO, CLASIFICACION_FINAL, ENTIDAD_RES, MUNICIPIO_RES FROM covidhistorico.datoscovid_sureste')
    )
    AS datos
    WHERE 
        (YEAR(FECHA_INGRESO) = 2020 OR YEAR(FECHA_INGRESO) = 2021) 
        AND MONTH(FECHA_INGRESO) < 13 
        AND (CLASIFICACION_FINAL IN ('1', '2', '3') OR CLASIFICACION_FINAL IN ('6')) 
    GROUP BY YEAR(FECHA_INGRESO), MONTH(FECHA_INGRESO), ENTIDAD_RES, MUNICIPIO_RES
) A
WHERE A.RowNum = 1 OR A.RowNum = 2
ORDER BY A.ENTIDAD_RES COLLATE SQL_Latin1_General_CP1_CI_AS, A.MES;